# Generated by Django 4.2.1 on 2023-05-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('adult', models.BooleanField()),
                ('title', models.CharField(max_length=30)),
                ('original_title', models.CharField(max_length=30, null=True)),
                ('overview', models.TextField()),
                ('tagline', models.TextField()),
                ('runtime', models.IntegerField()),
                ('release_date', models.DateField()),
                ('backdrop_path', models.TextField(null=True)),
                ('poster_path', models.TextField(null=True)),
                ('status', models.CharField(max_length=20)),
                ('vote_average', models.FloatField()),
                ('vote_count', models.IntegerField()),
                ('actors', models.ManyToManyField(related_name='movies', to='actors.actor')),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.genre')),
            ],
        ),
    ]
