# Generated by Django 4.2.1 on 2023-05-25 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('birthday', models.DateField(null=True)),
                ('deathday', models.DateField(null=True)),
                ('profile_path', models.TextField(null=True)),
            ],
        ),
    ]
